language: go
group: edge

go:
  - 1.9.x
  - tip

env:
  global:
    - CGO_ENABLED=0

install:
  - go get ./...

script:
  - make

notifications:
  email:
    on_success: change
    on_failure: always

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: EZ1gBuQw0apUwKhyX5jvrMkd81TbeQaEwcvXu8sU7T3XI2cR80COPf/WZ6Iqq7CJWOIAT08Z+RNSxtJJxQDLhQCpTp6icuFfRhahNWciUGhkKCmI+F213NGWVlJPw6pMWZHk2FPL6oTtwNz1xv1qIUNb4HPPxq0PEd2/bPR0O/WZRy/Fzp5TTqbq3u9X6rPD3r3rzTGbSPzPYZKvGdyoSE3vgt8UjB8zw9885K54OrridikvuESJaVzG0fwM/qaUExqjATlLBRyEynHuS7n2XPyZ9hF3OErUEvkwHpONiVBi4i8dRInwOX2aLWqi3FxRVhzaD0K5j47/zuBWqP2PiFvRILUjlkSzczgn3JSevDjs93+2hVHgzjO1NrGp+sbRhgkivZU5dU9pe9m3RoT5j+JHk/owhd/TjEiNBc9X70g6CpLkzwZQVUapTdFEwkVpFV7QHG1R8wiQXg+ZmQztxFbE9HekyYP+lmNjlMY1S0xwzdufhmpZmWXL4XuqLFZT/BDrRoilyhWev2jiAtGh5/ZwqjTmBOBCp4nsBJyc9RROqurV5T642EXoUNwxTArAtgpm4thgv3lzB9YFlcuOCCli5RR55pIfOOnM8ak3aLI+C5Z8/4OTCDokS4sIkJTxbe2qFarFX10h/HNbA0uB91AA0al52jXBRoYt+96Q4w0=
    file:
      - gbl_darwin_amd64
      - gbl_linux_386
      - gbl_linux_amd64
      - gbl_windows_386.exe
      - gbl_windows_amd64.exe
    on:
      tags: true
      repo: acgers/go-bilibili-live
      condition: $TRAVIS_GO_VERSION =~ ^1\.9
